### ISSUE TITLE
logic control (arduino  code)

### ISSUE THREAD

**Issue by Helo88** [Helo88/ASUMobiCarG13#3]
this code is to control motors using l298N (motor driver)

**Comment by doaamagdi** [comment]
http://howtomechatronics.com/tutorials/arduino/arduino-dc-motor-control-tutorial-l298n-pwm-h-bridge/

check this :dancing_women:

**Comment by Shoroukmohamed** [comment]
https://www.auselectronicsdirect.com.au/assets/files/TA0135%20V1.1_reduced%20size.pdf

what about it?
