### ISSUE TITLE
sheet 1

### ISSUE THREAD

**Issue by Helo88** [Helo88/ASUMobiCarG13#5]

**Comment by Helo88** [comment]
![sheet1 part2](https://user-images.githubusercontent.com/36270987/36398778-6984335e-15d1-11e8-8d94-13610c8b6364.JPG)

**Comment by Helo88** [comment]
![lolo](https://user-images.githubusercontent.com/36270987/36398940-3276d140-15d2-11e8-9aea-140ad1be6ebb.JPG)

**Comment by shimaa-mahmoud** [comment]
![aviary photo_131635523563130898](https://user-images.githubusercontent.com/29403082/36399408-71415146-15d4-11e8-874a-6561babd30c8.png)

**Comment by shimaa-mahmoud** [comment]
![scrolling leds](https://user-images.githubusercontent.com/29403082/36399530-ea62c212-15d4-11e8-8480-7706e4a923e7.png)

**Comment by shimaa-mahmoud** [comment]
![aviary photo_131635543357532099](https://user-images.githubusercontent.com/29403082/36400352-14a3a1b4-15d9-11e8-8126-bfe77dbe4913.png)

**Comment by nourhanKg** [comment]
``
![led with switch](https://user-images.githubusercontent.com/36276898/36427475-f2693f6e-1655-11e8-8d53-d0d13edbd098.png)

**Comment by nourhanKg** [comment]
![default](https://user-images.githubusercontent.com/36276898/36427640-6fa78940-1656-11e8-84a9-d3dfa2dfdded.png)

**Comment by doaamagdi** [comment]
`void setup(){
}
void Loop(){

for ( int u=4 ;u<=7 ; u++){

digitalWrite(u,HIGH);
delay(1000);
digitalWrite(u,LOW);
delay(1000);

}
for(int u=7; u>5 ; u--){

digitalWrite(u-1,HIGH);
delay(1000);
digitalWrite(u-1,LOW);
delay(1000);

}
}`

**Comment by doaamagdi** [comment]
ASUMobiCarG13/Arduino Examples/Doaa/sheet 1 (Q2)

**Comment by doaamagdi** [comment]
https://github.com/Helo88/ASUMobiCarG13/blob/master/Arduino%20Examples/Doaa/sheet%201%20(Q2)
https://github.com/Helo88/ASUMobiCarG13/blob/master/Arduino%20Examples/Doaa/blink%20LED%20%2Csheet%201%20(Q1)

**Comment by Rana2** [comment]
Q1 :https://github.com/Helo88/ASUMobiCarG13/tree/master/Arduino%20Examples/Rana/Q1

Q2: https://github.com/Helo88/ASUMobiCarG13/tree/master/Arduino%20Examples/Rana/Q2
